server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: Qm9Z8l@Jt4!rX2#ZxLw7*UqNpVe5$AbCdFgHiJkLmNoPqRsTuVwXyZ1234567890
  expiration: 36000000 # 10 sati traje